/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.views;

/**
 *
 * @author Cetecom
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAgregarProducto = new javax.swing.JMenuItem();
        mnuEditarProducto = new javax.swing.JMenuItem();
        mnuEliminarProducto = new javax.swing.JMenuItem();
        mnuListarProducto = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Producto");

        mnuAgregarProducto.setText("Agregar");
        mnuAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAgregarProducto);

        mnuEditarProducto.setText("Editar");
        jMenu1.add(mnuEditarProducto);

        mnuEliminarProducto.setText("Eliminar");
        jMenu1.add(mnuEliminarProducto);

        mnuListarProducto.setText("Listar");
        mnuListarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuListarProducto);

        jMenuBar1.add(jMenu1);

        mnSalir.setText("Salir");
        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuListarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarProductoActionPerformed
        // TODO add your handling code here:
        ListarProducto l = new ListarProducto();
        
        l.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_mnuListarProductoActionPerformed

    private void mnuAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarProductoActionPerformed
        AgregarProducto a = new AgregarProducto();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenuItem mnuAgregarProducto;
    private javax.swing.JMenuItem mnuEditarProducto;
    private javax.swing.JMenuItem mnuEliminarProducto;
    private javax.swing.JMenuItem mnuListarProducto;
    // End of variables declaration//GEN-END:variables
}
